"use strict";
const DATA_URL = "data/worldcup.json";
const CACHE_KEY = "wc2026_ngocsonle_cache_v3";
const state = { data: null, selectedDate: "", filter: "all", chartPoints: [] };
const $ = id => document.getElementById(id);
const el = {
  refreshBtn: $("refreshBtn"), importBtn: $("importBtn"), exportBtn: $("exportBtn"), statusPill: $("statusPill"), updatedAt: $("updatedAt"),
  heroMatches: $("heroMatches"), dayMatches: $("dayMatches"), dayScored: $("dayScored"), dayGoals: $("dayGoals"), dayAverage: $("dayAverage"), dayShare: $("dayShare"),
  selectedDateTitle: $("selectedDateTitle"), selectedDateBadge: $("selectedDateBadge"), prevDate: $("prevDate"), nextDate: $("nextDate"), dateSelect: $("dateSelect"), statusFilter: $("statusFilter"), matchesList: $("matchesList"),
  thirdPlaceBody: $("thirdPlaceBody"), standingsGrid: $("standingsGrid"), totalPlayed: $("totalPlayed"), totalGoals: $("totalGoals"), overallAverage: $("overallAverage"), bestDayGoals: $("bestDayGoals"), bestDayLabel: $("bestDayLabel"),
  goalsChart: $("goalsChart"), dailyStatsBody: $("dailyStatsBody"), importModal: $("importModal"), closeModal: $("closeModal"), jsonFile: $("jsonFile"), loadJsonBtn: $("loadJsonBtn"), toast: $("toast")
};
const collator = new Intl.Collator("en", { sensitivity: "base" });
function esc(v){return String(v??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));}
function num(v, fallback=0){const n=Number(v);return Number.isFinite(n)?n:fallback;}
function showToast(msg){el.toast.textContent=msg;el.toast.classList.add("show");clearTimeout(showToast.t);showToast.t=setTimeout(()=>el.toast.classList.remove("show"),2600);}
function setStatus(type,text){el.statusPill.className=`status-pill ${type}`;el.statusPill.innerHTML=`<span></span>${esc(text)}`;}
function flagEmoji(iso2){const c=String(iso2||"").toUpperCase();if(c==="SCO")return "🏴";if(!/^[A-Z]{2}$/.test(c)||c==="TBD")return "🏳️";return [...c].map(x=>String.fromCodePoint(127397+x.charCodeAt())).join("");}
function formatDate(key,long=true){if(!key)return "—";const [y,m,d]=key.split("-").map(Number);const dt=new Date(y,m-1,d);return new Intl.DateTimeFormat("vi-VN",long?{weekday:"long",day:"2-digit",month:"2-digit",year:"numeric"}:{day:"2-digit",month:"2-digit"}).format(dt);}
function isScored(m){return ["finished","live"].includes(m.status)&&Number.isFinite(Number(m.score?.home))&&Number.isFinite(Number(m.score?.away));}
function scoredMatches(){return state.data.matches.filter(isScored);}
function allDates(){return [...new Set(state.data.matches.map(m=>m.date_vn).filter(Boolean))].sort();}
function chooseDate(dates){const today=new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Ho_Chi_Minh",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date());if(dates.includes(today))return today;const completed=dates.filter(d=>state.data.matches.some(m=>m.date_vn===d&&isScored(m)));if(completed.length)return completed.at(-1);return dates.find(d=>d>=today)||dates.at(-1)||"";}
function normalizeData(raw){const data=raw&&typeof raw==="object"?raw:{};data.meta=data.meta||{};data.teams=Array.isArray(data.teams)?data.teams:[];data.matches=Array.isArray(data.matches)?data.matches:[];data.matches=data.matches.map((m,i)=>({id:String(m.id??i+1),stage:m.stage||"group",group:String(m.group||"").toUpperCase(),matchday:num(m.matchday),kickoff_utc:m.kickoff_utc||"",date_vn:m.date_vn||"",time_vn:m.time_vn||"",status:["finished","live","upcoming"].includes(m.status)?m.status:"upcoming",elapsed:m.elapsed||"",home:{id:String(m.home?.id??""),name:m.home?.name||"Chưa xác định",code:m.home?.code||"",iso2:m.home?.iso2||""},away:{id:String(m.away?.id??""),name:m.away?.name||"Chưa xác định",code:m.away?.code||"",iso2:m.away?.iso2||""},score:{home:m.score?.home===null||m.score?.home===undefined?null:num(m.score.home),away:m.score?.away===null||m.score?.away===undefined?null:num(m.score.away)},venue:m.venue||""}));return data;}
function saveCache(){try{localStorage.setItem(CACHE_KEY,JSON.stringify(state.data));}catch(e){console.warn(e);}}
function loadCache(){try{const raw=localStorage.getItem(CACHE_KEY);if(!raw)return false;state.data=normalizeData(JSON.parse(raw));return state.data.matches.length>0;}catch{return false;}}
async function loadData({manual=false}={}){el.refreshBtn.disabled=true;setStatus("loading",manual?"Đang tải dữ liệu mới":"Đang mở dữ liệu");const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),15000);try{const res=await fetch(`${DATA_URL}?v=${Date.now()}`,{cache:"no-store",signal:controller.signal});if(!res.ok)throw new Error(`HTTP ${res.status}`);const data=normalizeData(await res.json());if(!data.matches.length)throw new Error("File dữ liệu chưa có trận đấu");state.data=data;saveCache();renderAll(true);const isStarter=(data.meta?.source||"").includes("mẫu");setStatus(isStarter?"warning":"ok",isStarter?"Dữ liệu mẫu — hãy chạy GitHub Actions":`Đã tải ${data.matches.length} trận`);if(manual)showToast("Đã tải dữ liệu mới nhất trên website");}catch(err){console.error(err);if(!state.data&&loadCache()){renderAll(true);setStatus("warning","Mạng lỗi — đang dùng dữ liệu đã lưu");showToast("Đã mở dữ liệu gần nhất trên thiết bị");}else if(state.data){setStatus("warning","Chưa tải được bản mới — giữ dữ liệu hiện có");if(manual)showToast("Chưa tải được dữ liệu mới");}else{setStatus("error","Không đọc được dữ liệu");renderEmpty();showToast("Kiểm tra GitHub Actions và thử lại");}}finally{clearTimeout(timer);el.refreshBtn.disabled=false;}}
function renderAll(resetDate=false){if(!state.data)return;const dates=allDates();if(resetDate||!dates.includes(state.selectedDate))state.selectedDate=chooseDate(dates);renderDateControl(dates);renderResults();renderStandings();renderGoals();renderMeta();}
function renderMeta(){const meta=state.data.meta||{};const d=meta.updated_at?new Date(meta.updated_at):null;el.updatedAt.textContent=d&&!Number.isNaN(d.getTime())?`${meta.source||"Dữ liệu website"} • ${new Intl.DateTimeFormat("vi-VN",{dateStyle:"short",timeStyle:"short",timeZone:"Asia/Ho_Chi_Minh"}).format(d)}`:(meta.source||"Chưa cập nhật");el.heroMatches.textContent=scoredMatches().length;}
function renderDateControl(dates){el.dateSelect.innerHTML=dates.map(d=>`<option value="${d}" ${d===state.selectedDate?"selected":""}>${esc(formatDate(d))}</option>`).join("");const idx=dates.indexOf(state.selectedDate);el.prevDate.disabled=idx<=0;el.nextDate.disabled=idx<0||idx>=dates.length-1;}
function dailySummary(date){const matches=state.data.matches.filter(m=>m.date_vn===date);const scored=matches.filter(isScored);const goals=scored.reduce((s,m)=>s+num(m.score.home)+num(m.score.away),0);const scoring=scored.filter(m=>num(m.score.home)+num(m.score.away)>0).length;return{date,matches,scored,goals,scoring,avg:scored.length?goals/scored.length:0};}
function overallSummary(){const scored=scoredMatches();const goals=scored.reduce((s,m)=>s+num(m.score.home)+num(m.score.away),0);return{scored,goals,avg:scored.length?goals/scored.length:0};}
function stageText(m){if(m.stage==="group")return m.group?`Bảng ${m.group}`:"Vòng bảng";const map={r32:"Vòng 32 đội",r16:"Vòng 16 đội",qf:"Tứ kết",sf:"Bán kết",third:"Tranh hạng ba",final:"Chung kết"};return map[m.stage]||m.stage||"World Cup";}
function statusText(m){if(m.status==="finished")return "Kết thúc";if(m.status==="live")return m.elapsed||"Đang đấu";return "Sắp đấu";}
function renderResults(){const sum=dailySummary(state.selectedDate);const overall=overallSummary();el.dayMatches.textContent=sum.matches.length;el.dayScored.textContent=`${sum.scored.length} trận có tỷ số`;el.dayGoals.textContent=sum.goals;el.dayAverage.textContent=sum.avg.toFixed(2);el.dayShare.textContent=`${overall.goals?(sum.goals/overall.goals*100).toFixed(1):"0.0"}%`;el.selectedDateTitle.textContent=formatDate(state.selectedDate);el.selectedDateBadge.textContent=formatDate(state.selectedDate,false);const list=sum.matches.filter(m=>state.filter==="all"||m.status===state.filter).sort((a,b)=>(a.time_vn||"99:99").localeCompare(b.time_vn||"99:99"));if(!list.length){el.matchesList.innerHTML='<div class="empty-state">Không có trận phù hợp với bộ lọc trong ngày này.</div>';return;}el.matchesList.innerHTML=list.map(m=>{const score=isScored(m)?`<div class="score">${num(m.score.home)} – ${num(m.score.away)}</div>`:`<div class="score upcoming">${esc(m.time_vn||"Chờ giờ")}</div>`;return`<article class="match-card ${m.status}"><div class="team"><span class="flag-emoji">${flagEmoji(m.home.iso2)}</span><span class="team-name">${esc(m.home.name)}</span></div><div class="score-block">${score}<div class="match-meta">${esc(stageText(m))}${m.venue?` · ${esc(m.venue)}`:""}</div><span class="match-status ${m.status}">${esc(statusText(m))}</span></div><div class="team away"><span class="team-name">${esc(m.away.name)}</span><span class="flag-emoji">${flagEmoji(m.away.iso2)}</span></div></article>`;}).join("");}
function teamSeed(){const groups=new Map();for(const t of state.data.teams){const g=String(t.group||"").toUpperCase();if(!/^[A-L]$/.test(g))continue;if(!groups.has(g))groups.set(g,new Map());groups.get(g).set(String(t.id),{teamId:String(t.id),name:t.name,code:t.code||"",iso2:t.iso2||"",played:0,wins:0,draws:0,losses:0,gf:0,ga:0,gd:0,points:0});}for(const m of state.data.matches){if(m.stage!=="group"||!m.group)continue;if(!groups.has(m.group))groups.set(m.group,new Map());for(const side of [m.home,m.away]){if(!groups.get(m.group).has(String(side.id)))groups.get(m.group).set(String(side.id),{teamId:String(side.id),name:side.name,code:side.code||"",iso2:side.iso2||"",played:0,wins:0,draws:0,losses:0,gf:0,ga:0,gd:0,points:0});}}return groups;}
function rankSort(a,b){return b.points-a.points||b.gd-a.gd||collator.compare(a.name,b.name);}
function computeStandings(){const groups=teamSeed();for(const m of state.data.matches){if(m.stage!=="group"||!m.group||!isScored(m))continue;const g=groups.get(m.group);const h=g?.get(String(m.home.id));const a=g?.get(String(m.away.id));if(!h||!a)continue;const hs=num(m.score.home),as=num(m.score.away);h.played++;a.played++;h.gf+=hs;h.ga+=as;a.gf+=as;a.ga+=hs;if(hs>as){h.wins++;a.losses++;h.points+=3;}else if(hs<as){a.wins++;h.losses++;a.points+=3;}else{h.draws++;a.draws++;h.points++;a.points++;}}return [...groups.entries()].sort(([a],[b])=>a.localeCompare(b)).map(([group,map])=>({group,rows:[...map.values()].map(r=>({...r,gd:r.gf-r.ga})).sort(rankSort)}));}
function rowTeam(r){return`<div class="table-team"><span class="flag-emoji">${flagEmoji(r.iso2)}</span><span>${esc(r.name)}</span></div>`;}
function renderStandings(){const groups=computeStandings();const thirds=groups.map(g=>g.rows[2]?{...g.rows[2],group:g.group}:null).filter(Boolean).sort(rankSort);el.thirdPlaceBody.innerHTML=thirds.length?thirds.map((r,i)=>`<tr class="${i<8?"qualified":""}"><td class="rank">${i+1}</td><td class="team-cell">${rowTeam(r)}<small style="color:var(--muted);margin-left:43px">Bảng ${esc(r.group)}</small></td><td class="points">${r.points}</td><td>${r.gd>0?"+":""}${r.gd}</td></tr>`).join(""):'<tr><td colspan="4">Chưa có dữ liệu.</td></tr>';el.standingsGrid.innerHTML=groups.map(g=>`<article class="group-card glass"><h3 class="group-title">Bảng ${g.group}</h3><div class="table-scroll"><table class="rank-table"><thead><tr><th>#</th><th>Đội</th><th>TR</th><th>T</th><th>H</th><th>B</th><th>BT</th><th>BB</th><th>HS</th><th>Đ</th></tr></thead><tbody>${g.rows.map((r,i)=>`<tr class="${i<2?"qualify":i===2?"third":""}"><td class="rank">${i+1}</td><td class="team-cell">${rowTeam(r)}</td><td>${r.played}</td><td>${r.wins}</td><td>${r.draws}</td><td>${r.losses}</td><td>${r.gf}</td><td>${r.ga}</td><td>${r.gd>0?"+":""}${r.gd}</td><td class="points">${r.points}</td></tr>`).join("")}</tbody></table></div></article>`).join("");}
function renderGoals(){const overall=overallSummary();const rows=allDates().map(d=>dailySummary(d)).filter(x=>x.scored.length);el.totalPlayed.textContent=overall.scored.length;el.totalGoals.textContent=overall.goals;el.overallAverage.textContent=overall.avg.toFixed(2);const best=rows.reduce((a,b)=>!a||b.goals>a.goals?b:a,null);el.bestDayGoals.textContent=best?.goals||0;el.bestDayLabel.textContent=best?formatDate(best.date,false):"Chưa có dữ liệu";el.dailyStatsBody.innerHTML=rows.length?rows.map(r=>`<tr><td>${esc(formatDate(r.date,false))}</td><td>${r.scored.length}</td><td class="points">${r.goals}</td><td>${r.avg.toFixed(2)}</td><td>${r.scoring}/${r.scored.length}</td><td>${overall.goals?(r.goals/overall.goals*100).toFixed(1):"0.0"}%</td></tr>`).join(""):'<tr><td colspan="6">Chưa có trận có tỷ số.</td></tr>';state.chartPoints=rows;drawChart();}
function drawChart(){const canvas=el.goalsChart;if(!canvas)return;const rect=canvas.getBoundingClientRect();const dpr=Math.max(1,Math.min(2,window.devicePixelRatio||1));canvas.width=Math.max(320,rect.width*dpr);canvas.height=Math.max(240,rect.height*dpr);const ctx=canvas.getContext("2d");ctx.scale(dpr,dpr);const w=canvas.width/dpr,h=canvas.height/dpr;ctx.clearRect(0,0,w,h);const rows=state.chartPoints;if(!rows.length){ctx.fillStyle="#9bb7aa";ctx.font="14px system-ui";ctx.textAlign="center";ctx.fillText("Chưa có dữ liệu bàn thắng",w/2,h/2);return;}const pad={l:36,r:14,t:20,b:42};const max=Math.max(1,...rows.map(r=>r.goals));const gap=8;const bw=Math.max(12,(w-pad.l-pad.r-gap*(rows.length-1))/rows.length);ctx.strokeStyle="rgba(166,255,218,.12)";ctx.fillStyle="#8fb3a4";ctx.font="11px system-ui";ctx.textAlign="right";for(let i=0;i<=4;i++){const y=pad.t+(h-pad.t-pad.b)*i/4;ctx.beginPath();ctx.moveTo(pad.l,y);ctx.lineTo(w-pad.r,y);ctx.stroke();const val=Math.round(max*(1-i/4));ctx.fillText(String(val),pad.l-7,y+4);}rows.forEach((r,i)=>{const x=pad.l+i*(bw+gap);const bh=(h-pad.t-pad.b)*(r.goals/max);const y=h-pad.b-bh;const grad=ctx.createLinearGradient(0,y,0,h-pad.b);grad.addColorStop(0,"#63efb6");grad.addColorStop(1,"#1ebf82");ctx.fillStyle=grad;roundRect(ctx,x,y,bw,bh,6);ctx.fill();if(rows.length<=18||i%2===0){ctx.save();ctx.translate(x+bw/2,h-pad.b+12);ctx.rotate(-Math.PI/5);ctx.fillStyle="#9bb7aa";ctx.font="10px system-ui";ctx.textAlign="right";ctx.fillText(formatDate(r.date,false),0,0);ctx.restore();}ctx.fillStyle="#f4fff9";ctx.font="bold 11px system-ui";ctx.textAlign="center";ctx.fillText(String(r.goals),x+bw/2,Math.max(13,y-5));});}
function roundRect(ctx,x,y,w,h,r){const rr=Math.min(r,w/2,h/2);ctx.beginPath();ctx.moveTo(x+rr,y);ctx.arcTo(x+w,y,x+w,y+h,rr);ctx.arcTo(x+w,y+h,x,y+h,rr);ctx.arcTo(x,y+h,x,y,rr);ctx.arcTo(x,y,x+w,y,rr);ctx.closePath();}
function renderEmpty(){el.matchesList.innerHTML='<div class="empty-state">Chưa có dữ liệu. Hãy chạy workflow GitHub Actions hoặc nhập file JSON.</div>';el.standingsGrid.innerHTML="";el.thirdPlaceBody.innerHTML='<tr><td colspan="4">Chưa có dữ liệu.</td></tr>';}
function exportData(){if(!state.data)return;const blob=new Blob([JSON.stringify(state.data,null,2)],{type:"application/json"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=`worldcup-2026-${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}
function openModal(){el.importModal.hidden=false;}
function closeModal(){el.importModal.hidden=true;el.jsonFile.value="";}
async function importJson(){const file=el.jsonFile.files?.[0];if(!file){showToast("Hãy chọn một file JSON");return;}try{const data=normalizeData(JSON.parse(await file.text()));if(!data.matches.length)throw new Error("Không có trận đấu");state.data=data;saveCache();renderAll(true);setStatus("ok","Đang dùng dữ liệu JSON đã nhập");closeModal();showToast("Đã nạp dữ liệu thành công");}catch(e){console.error(e);showToast("File JSON không hợp lệ");}}
document.querySelectorAll(".tab").forEach(btn=>btn.addEventListener("click",()=>{document.querySelectorAll(".tab").forEach(x=>x.classList.toggle("active",x===btn));document.querySelectorAll(".tab-panel").forEach(p=>p.classList.toggle("active",p.id===btn.dataset.tab));if(btn.dataset.tab==="goals")requestAnimationFrame(drawChart);}));
el.refreshBtn.addEventListener("click",()=>loadData({manual:true}));el.importBtn.addEventListener("click",openModal);el.exportBtn.addEventListener("click",exportData);el.closeModal.addEventListener("click",closeModal);el.importModal.addEventListener("click",e=>{if(e.target===el.importModal)closeModal();});el.loadJsonBtn.addEventListener("click",importJson);el.dateSelect.addEventListener("change",e=>{state.selectedDate=e.target.value;renderAll();});el.statusFilter.addEventListener("change",e=>{state.filter=e.target.value;renderResults();});el.prevDate.addEventListener("click",()=>{const d=allDates(),i=d.indexOf(state.selectedDate);if(i>0){state.selectedDate=d[i-1];renderAll();}});el.nextDate.addEventListener("click",()=>{const d=allDates(),i=d.indexOf(state.selectedDate);if(i>=0&&i<d.length-1){state.selectedDate=d[i+1];renderAll();}});window.addEventListener("resize",()=>{clearTimeout(window.__chartTimer);window.__chartTimer=setTimeout(drawChart,120);});
loadData();
